language: ruby
before_script: "gem install --no-ri --no-rdoc bundler"
script: "rake spec"
notifications:
  email: false
rvm:
  - 1.9.3
  - 1.8.7
env:
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=3.1.0
gemfile: Gemfile
branches:
  only:
    - spec_units
